version: '3'
services:
    database:
      build: .
      restart: always
      container_name: database
      environment:
            - MYSQL_ROOT_PASSWORD=foodrandsql
      volumes:
            - ./script/:/docker-entrypoint-initdb.d
            - ./script/mysql-data:/var/lib/mysql
      ports:
            - '3306:3306'
networks:
    default:
      external:
            name: foodrandnetwork